
title: whdzera
email: whdzera@gmail.com
baseurl: "/jekyll-ai-message" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: whdzera
github_username:  rokhimin/jekyll-ai-message

permalink: /:title.rb
files: "/jekyll-ai-message"